apiVersion: apps/v1
kind: Deployment
metadata:
  name: autos-siyun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autos-siyun
  template:
    metadata:
      labels:
        app: autos-siyun
    spec:
      containers:
        - image: $IMAGE
          name: autos-siyun
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: 52.26.72.203
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: autos-siyun-mysql-secret
                  key: db_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: autos-siyun-mysql-secret
                  key: db_user
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: autos-siyun-mysql-secret
                  key: db_pwd
      imagePullSecrets: # Be sure the token name matches what you created on K8s
        - name: autos-siyun-deploy-token
