apiVersion: v1
kind: Service
metadata:
  name: autos-siyun-lb
spec:
  type: LoadBalancer
  selector:
    app: autos-siyun
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http